<?php
/**
 * generate_report.php - Report Generation Interface
 * 
 * Generates and displays reports in HTML, PDF, or CSV format
 */

require_once __DIR__ . '/admin_auth.php';
require_once __DIR__ . '/../config/db_connect.php';
require_once __DIR__ . '/../modules/ReportGenerator.php';
require_once __DIR__ . '/../modules/IncidentReportTemplate.php';
require_once __DIR__ . '/../modules/CaseReportGenerator.php';
require_once __DIR__ . '/../modules/BCPCReportGenerator.php';

$report_type = $_GET['type'] ?? 'incident';
$from = $_GET['from'] ?? date('Y-01-01');
$to = $_GET['to'] ?? date('Y-m-d');
$format = $_GET['format'] ?? 'html';

try {
    
    switch ($report_type) {
        
        case 'incident':
            $report = new IncidentReportTemplate($pdo, 'standard');
            $report->setDateRange($from, $to);
            $report->setMetadata('Generated By', $_SESSION['fullname'] ?? 'System');
            $report->setMetadata('Report Type', 'Incident Summary Report');
            
            if ($format === 'csv') {
                echo $report->generateCsv('incident_report_' . date('Y-m-d') . '.csv');
            } else {
                $html = $report->getSummaryTemplate();
                header('Content-Type: text/html; charset=utf-8');
                echo $html;
            }
            break;
        
        case 'case':
            $report = new CaseReportGenerator($pdo);
            $report->setDateRange($from, $to);
            $report->setMetadata('Generated By', $_SESSION['fullname'] ?? 'System');
            $report->setMetadata('Report Type', 'Case Status Report');
            
            $html = $report->generateHtml();
            header('Content-Type: text/html; charset=utf-8');
            echo $html;
            break;
        
        case 'bcpc':
            $month = $_GET['month'] ?? date('m');
            $year = $_GET['year'] ?? date('Y');
            
            $report = new BCPCReportGenerator($pdo, $month, $year);
            $report->setBarangay(
                $_GET['barangay'] ?? 'Barangay',
                $_GET['municipality'] ?? '',
                $_GET['province'] ?? ''
            );
            $report->setMetadata('Generated By', $_SESSION['fullname'] ?? 'System');
            
            $html = $report->generateBCPCHtml();
            header('Content-Type: text/html; charset=utf-8');
            echo $html;
            break;
        
        case 'export':
            // HTML export (printable)
            $report = new IncidentReportTemplate($pdo, 'standard');
            $report->setDateRange($from, $to);
            $report->setMetadata('Generated By', $_SESSION['fullname'] ?? 'System');
            
            $html = $report->getSummaryTemplate();
            header('Content-Type: text/html; charset=utf-8');
            echo $html;
            break;
        
        default:
            header('Location: analytics_dashboard.php');
            exit;
    }
    
} catch (Exception $e) {
    error_log('Report generation error: ' . $e->getMessage());
    header('Location: analytics_dashboard.php?error=report_generation_failed');
    exit;
}
